//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuKuangService.fileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="fileService.WebServiceFileSoap")]
    public interface WebServiceFileSoap {
        
        // CODEGEN: 参数“fileBytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LuKuangService.fileService.UploadFileResponse UploadFile(LuKuangService.fileService.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<LuKuangService.fileService.UploadFileResponse> UploadFileAsync(LuKuangService.fileService.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DrawPicture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DrawPicture(int r_id, string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DrawPicture", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DrawPictureAsync(int r_id, string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendImgToELD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendImgToELD(string fileName, LuKuangService.fileService.MyTDeviceParam myTDeviceParam, LuKuangService.fileService.ELDRegion[] arrEldRegion, LuKuangService.fileService.LeafObj[] arrleaf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendImgToELD", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendImgToELDAsync(string fileName, LuKuangService.fileService.MyTDeviceParam myTDeviceParam, LuKuangService.fileService.ELDRegion[] arrEldRegion, LuKuangService.fileService.LeafObj[] arrleaf);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] fileBytes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fileName;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(byte[] fileBytes, string fileName) {
            this.fileBytes = fileBytes;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UploadFileResult;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(string UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MyTDeviceParam : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int devTypeField;
        
        private int locPortField;
        
        private string rmtHostField;
        
        private int rmtPortField;
        
        private int dstAddrField;
        
        private int displayTypeField;
        
        private int r_idField;
        
        private string r_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int devType {
            get {
                return this.devTypeField;
            }
            set {
                this.devTypeField = value;
                this.RaisePropertyChanged("devType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int locPort {
            get {
                return this.locPortField;
            }
            set {
                this.locPortField = value;
                this.RaisePropertyChanged("locPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string rmtHost {
            get {
                return this.rmtHostField;
            }
            set {
                this.rmtHostField = value;
                this.RaisePropertyChanged("rmtHost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int rmtPort {
            get {
                return this.rmtPortField;
            }
            set {
                this.rmtPortField = value;
                this.RaisePropertyChanged("rmtPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int dstAddr {
            get {
                return this.dstAddrField;
            }
            set {
                this.dstAddrField = value;
                this.RaisePropertyChanged("dstAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int displayType {
            get {
                return this.displayTypeField;
            }
            set {
                this.displayTypeField = value;
                this.RaisePropertyChanged("displayType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int r_id {
            get {
                return this.r_idField;
            }
            set {
                this.r_idField = value;
                this.RaisePropertyChanged("r_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string r_name {
            get {
                return this.r_nameField;
            }
            set {
                this.r_nameField = value;
                this.RaisePropertyChanged("r_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClockPro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int leftField;
        
        private int topField;
        
        private int widthField;
        
        private int heightField;
        
        private int transparentField;
        
        private int borderField;
        
        private int offsetField;
        
        private ushort bkcolorField;
        
        private ushort bordercolorField;
        
        private ushort borderwidthField;
        
        private int bordershapeField;
        
        private int dotradiusField;
        
        private int adotwidthField;
        
        private ushort adotcolorField;
        
        private int bdotwidthField;
        
        private ushort bdotcolorField;
        
        private int hourwidthField;
        
        private ushort hourcolorField;
        
        private int minutewidthField;
        
        private ushort minutecolorField;
        
        private int secondwidthField;
        
        private ushort secondcolorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
                this.RaisePropertyChanged("top");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int transparent {
            get {
                return this.transparentField;
            }
            set {
                this.transparentField = value;
                this.RaisePropertyChanged("transparent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
                this.RaisePropertyChanged("border");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ushort bkcolor {
            get {
                return this.bkcolorField;
            }
            set {
                this.bkcolorField = value;
                this.RaisePropertyChanged("bkcolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public ushort bordercolor {
            get {
                return this.bordercolorField;
            }
            set {
                this.bordercolorField = value;
                this.RaisePropertyChanged("bordercolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public ushort borderwidth {
            get {
                return this.borderwidthField;
            }
            set {
                this.borderwidthField = value;
                this.RaisePropertyChanged("borderwidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int bordershape {
            get {
                return this.bordershapeField;
            }
            set {
                this.bordershapeField = value;
                this.RaisePropertyChanged("bordershape");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int dotradius {
            get {
                return this.dotradiusField;
            }
            set {
                this.dotradiusField = value;
                this.RaisePropertyChanged("dotradius");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int adotwidth {
            get {
                return this.adotwidthField;
            }
            set {
                this.adotwidthField = value;
                this.RaisePropertyChanged("adotwidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public ushort adotcolor {
            get {
                return this.adotcolorField;
            }
            set {
                this.adotcolorField = value;
                this.RaisePropertyChanged("adotcolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int bdotwidth {
            get {
                return this.bdotwidthField;
            }
            set {
                this.bdotwidthField = value;
                this.RaisePropertyChanged("bdotwidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public ushort bdotcolor {
            get {
                return this.bdotcolorField;
            }
            set {
                this.bdotcolorField = value;
                this.RaisePropertyChanged("bdotcolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int hourwidth {
            get {
                return this.hourwidthField;
            }
            set {
                this.hourwidthField = value;
                this.RaisePropertyChanged("hourwidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public ushort hourcolor {
            get {
                return this.hourcolorField;
            }
            set {
                this.hourcolorField = value;
                this.RaisePropertyChanged("hourcolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int minutewidth {
            get {
                return this.minutewidthField;
            }
            set {
                this.minutewidthField = value;
                this.RaisePropertyChanged("minutewidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public ushort minutecolor {
            get {
                return this.minutecolorField;
            }
            set {
                this.minutecolorField = value;
                this.RaisePropertyChanged("minutecolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int secondwidth {
            get {
                return this.secondwidthField;
            }
            set {
                this.secondwidthField = value;
                this.RaisePropertyChanged("secondwidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public ushort secondcolor {
            get {
                return this.secondcolorField;
            }
            set {
                this.secondcolorField = value;
                this.RaisePropertyChanged("secondcolor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DateTimePro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int alignmentField;
        
        private int leftField;
        
        private int topField;
        
        private int widthField;
        
        private int heightField;
        
        private int transparentField;
        
        private int borderField;
        
        private string fontnameField;
        
        private int fontsizeField;
        
        private int fontcolorField;
        
        private int fontstyleField;
        
        private int year_offsetField;
        
        private int month_offsetField;
        
        private int day_offsetField;
        
        private int sec_offsetField;
        
        private string formatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int alignment {
            get {
                return this.alignmentField;
            }
            set {
                this.alignmentField = value;
                this.RaisePropertyChanged("alignment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
                this.RaisePropertyChanged("top");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int transparent {
            get {
                return this.transparentField;
            }
            set {
                this.transparentField = value;
                this.RaisePropertyChanged("transparent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
                this.RaisePropertyChanged("border");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string fontname {
            get {
                return this.fontnameField;
            }
            set {
                this.fontnameField = value;
                this.RaisePropertyChanged("fontname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int fontsize {
            get {
                return this.fontsizeField;
            }
            set {
                this.fontsizeField = value;
                this.RaisePropertyChanged("fontsize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int fontcolor {
            get {
                return this.fontcolorField;
            }
            set {
                this.fontcolorField = value;
                this.RaisePropertyChanged("fontcolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int fontstyle {
            get {
                return this.fontstyleField;
            }
            set {
                this.fontstyleField = value;
                this.RaisePropertyChanged("fontstyle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int year_offset {
            get {
                return this.year_offsetField;
            }
            set {
                this.year_offsetField = value;
                this.RaisePropertyChanged("year_offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int month_offset {
            get {
                return this.month_offsetField;
            }
            set {
                this.month_offsetField = value;
                this.RaisePropertyChanged("month_offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int day_offset {
            get {
                return this.day_offsetField;
            }
            set {
                this.day_offsetField = value;
                this.RaisePropertyChanged("day_offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int sec_offset {
            get {
                return this.sec_offsetField;
            }
            set {
                this.sec_offsetField = value;
                this.RaisePropertyChanged("sec_offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("format");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PicturePro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int alignmentField;
        
        private int leftField;
        
        private int topField;
        
        private int widthField;
        
        private int heightField;
        
        private int transparentField;
        
        private int borderField;
        
        private string filenameField;
        
        private int inmethodField;
        
        private int inspeedField;
        
        private int outmethodField;
        
        private int outspeedField;
        
        private int stopmethodField;
        
        private int stopspeedField;
        
        private int stoptimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int alignment {
            get {
                return this.alignmentField;
            }
            set {
                this.alignmentField = value;
                this.RaisePropertyChanged("alignment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
                this.RaisePropertyChanged("top");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int transparent {
            get {
                return this.transparentField;
            }
            set {
                this.transparentField = value;
                this.RaisePropertyChanged("transparent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
                this.RaisePropertyChanged("border");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int inmethod {
            get {
                return this.inmethodField;
            }
            set {
                this.inmethodField = value;
                this.RaisePropertyChanged("inmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int inspeed {
            get {
                return this.inspeedField;
            }
            set {
                this.inspeedField = value;
                this.RaisePropertyChanged("inspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int outmethod {
            get {
                return this.outmethodField;
            }
            set {
                this.outmethodField = value;
                this.RaisePropertyChanged("outmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int outspeed {
            get {
                return this.outspeedField;
            }
            set {
                this.outspeedField = value;
                this.RaisePropertyChanged("outspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int stopmethod {
            get {
                return this.stopmethodField;
            }
            set {
                this.stopmethodField = value;
                this.RaisePropertyChanged("stopmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int stopspeed {
            get {
                return this.stopspeedField;
            }
            set {
                this.stopspeedField = value;
                this.RaisePropertyChanged("stopspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int stoptime {
            get {
                return this.stoptimeField;
            }
            set {
                this.stoptimeField = value;
                this.RaisePropertyChanged("stoptime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TextPro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int leftField;
        
        private int topField;
        
        private int alignmentField;
        
        private int widthField;
        
        private int heightField;
        
        private int transparentField;
        
        private int borderField;
        
        private string strField;
        
        private string fontnameField;
        
        private int fontsizeField;
        
        private int fontcolorField;
        
        private int fontstyleField;
        
        private int wordwrapField;
        
        private int inmethodField;
        
        private int inspeedField;
        
        private int outmethodField;
        
        private int outspeedField;
        
        private int stopmethodField;
        
        private int stopspeedField;
        
        private int stoptimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
                this.RaisePropertyChanged("top");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int alignment {
            get {
                return this.alignmentField;
            }
            set {
                this.alignmentField = value;
                this.RaisePropertyChanged("alignment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int transparent {
            get {
                return this.transparentField;
            }
            set {
                this.transparentField = value;
                this.RaisePropertyChanged("transparent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
                this.RaisePropertyChanged("border");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string str {
            get {
                return this.strField;
            }
            set {
                this.strField = value;
                this.RaisePropertyChanged("str");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string fontname {
            get {
                return this.fontnameField;
            }
            set {
                this.fontnameField = value;
                this.RaisePropertyChanged("fontname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int fontsize {
            get {
                return this.fontsizeField;
            }
            set {
                this.fontsizeField = value;
                this.RaisePropertyChanged("fontsize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int fontcolor {
            get {
                return this.fontcolorField;
            }
            set {
                this.fontcolorField = value;
                this.RaisePropertyChanged("fontcolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int fontstyle {
            get {
                return this.fontstyleField;
            }
            set {
                this.fontstyleField = value;
                this.RaisePropertyChanged("fontstyle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int wordwrap {
            get {
                return this.wordwrapField;
            }
            set {
                this.wordwrapField = value;
                this.RaisePropertyChanged("wordwrap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int inmethod {
            get {
                return this.inmethodField;
            }
            set {
                this.inmethodField = value;
                this.RaisePropertyChanged("inmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int inspeed {
            get {
                return this.inspeedField;
            }
            set {
                this.inspeedField = value;
                this.RaisePropertyChanged("inspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int outmethod {
            get {
                return this.outmethodField;
            }
            set {
                this.outmethodField = value;
                this.RaisePropertyChanged("outmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int outspeed {
            get {
                return this.outspeedField;
            }
            set {
                this.outspeedField = value;
                this.RaisePropertyChanged("outspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int stopmethod {
            get {
                return this.stopmethodField;
            }
            set {
                this.stopmethodField = value;
                this.RaisePropertyChanged("stopmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int stopspeed {
            get {
                return this.stopspeedField;
            }
            set {
                this.stopspeedField = value;
                this.RaisePropertyChanged("stopspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int stoptime {
            get {
                return this.stoptimeField;
            }
            set {
                this.stoptimeField = value;
                this.RaisePropertyChanged("stoptime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DisplayObj : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int objTypeIndexField;
        
        private TextPro textProField;
        
        private PicturePro pictureProField;
        
        private DateTimePro dateTimeProField;
        
        private ClockPro clockProField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ObjTypeIndex {
            get {
                return this.objTypeIndexField;
            }
            set {
                this.objTypeIndexField = value;
                this.RaisePropertyChanged("ObjTypeIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TextPro TextPro {
            get {
                return this.textProField;
            }
            set {
                this.textProField = value;
                this.RaisePropertyChanged("TextPro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PicturePro PicturePro {
            get {
                return this.pictureProField;
            }
            set {
                this.pictureProField = value;
                this.RaisePropertyChanged("PicturePro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DateTimePro DateTimePro {
            get {
                return this.dateTimeProField;
            }
            set {
                this.dateTimeProField = value;
                this.RaisePropertyChanged("DateTimePro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ClockPro ClockPro {
            get {
                return this.clockProField;
            }
            set {
                this.clockProField = value;
                this.RaisePropertyChanged("ClockPro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LeafObj : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int next_timeField;
        
        private DisplayObj[] displayObjListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Next_time {
            get {
                return this.next_timeField;
            }
            set {
                this.next_timeField = value;
                this.RaisePropertyChanged("Next_time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public DisplayObj[] DisplayObjList {
            get {
                return this.displayObjListField;
            }
            set {
                this.displayObjListField = value;
                this.RaisePropertyChanged("DisplayObjList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ELDRegion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int region_IndexField;
        
        private string eLD_IPField;
        
        private int road_idField;
        
        private int regionTypeField;
        
        private int topField;
        
        private int leftField;
        
        private int widthField;
        
        private int heightField;
        
        private int borderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Region_Index {
            get {
                return this.region_IndexField;
            }
            set {
                this.region_IndexField = value;
                this.RaisePropertyChanged("Region_Index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ELD_IP {
            get {
                return this.eLD_IPField;
            }
            set {
                this.eLD_IPField = value;
                this.RaisePropertyChanged("ELD_IP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int road_id {
            get {
                return this.road_idField;
            }
            set {
                this.road_idField = value;
                this.RaisePropertyChanged("road_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int RegionType {
            get {
                return this.regionTypeField;
            }
            set {
                this.regionTypeField = value;
                this.RaisePropertyChanged("RegionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
                this.RaisePropertyChanged("top");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
                this.RaisePropertyChanged("border");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceFileSoapChannel : LuKuangService.fileService.WebServiceFileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceFileSoapClient : System.ServiceModel.ClientBase<LuKuangService.fileService.WebServiceFileSoap>, LuKuangService.fileService.WebServiceFileSoap {
        
        public WebServiceFileSoapClient() {
        }
        
        public WebServiceFileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceFileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LuKuangService.fileService.UploadFileResponse LuKuangService.fileService.WebServiceFileSoap.UploadFile(LuKuangService.fileService.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public string UploadFile(byte[] fileBytes, string fileName) {
            LuKuangService.fileService.UploadFileRequest inValue = new LuKuangService.fileService.UploadFileRequest();
            inValue.fileBytes = fileBytes;
            inValue.fileName = fileName;
            LuKuangService.fileService.UploadFileResponse retVal = ((LuKuangService.fileService.WebServiceFileSoap)(this)).UploadFile(inValue);
            return retVal.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LuKuangService.fileService.UploadFileResponse> LuKuangService.fileService.WebServiceFileSoap.UploadFileAsync(LuKuangService.fileService.UploadFileRequest request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<LuKuangService.fileService.UploadFileResponse> UploadFileAsync(byte[] fileBytes, string fileName) {
            LuKuangService.fileService.UploadFileRequest inValue = new LuKuangService.fileService.UploadFileRequest();
            inValue.fileBytes = fileBytes;
            inValue.fileName = fileName;
            return ((LuKuangService.fileService.WebServiceFileSoap)(this)).UploadFileAsync(inValue);
        }
        
        public string DrawPicture(int r_id, string filename) {
            return base.Channel.DrawPicture(r_id, filename);
        }
        
        public System.Threading.Tasks.Task<string> DrawPictureAsync(int r_id, string filename) {
            return base.Channel.DrawPictureAsync(r_id, filename);
        }
        
        public string SendImgToELD(string fileName, LuKuangService.fileService.MyTDeviceParam myTDeviceParam, LuKuangService.fileService.ELDRegion[] arrEldRegion, LuKuangService.fileService.LeafObj[] arrleaf) {
            return base.Channel.SendImgToELD(fileName, myTDeviceParam, arrEldRegion, arrleaf);
        }
        
        public System.Threading.Tasks.Task<string> SendImgToELDAsync(string fileName, LuKuangService.fileService.MyTDeviceParam myTDeviceParam, LuKuangService.fileService.ELDRegion[] arrEldRegion, LuKuangService.fileService.LeafObj[] arrleaf) {
            return base.Channel.SendImgToELDAsync(fileName, myTDeviceParam, arrEldRegion, arrleaf);
        }
    }
}
